export const data = [
  { label: 1, text: "woman_N prepares_TV tasty_ADJ dinner_N" },
  { label: 1, text: "woman_N cooks_TV tasty_ADJ sauce_N" },
  { label: 0, text: "skillful_ADJ woman_N prepares_TV software_N" },
  { label: 1, text: "skillful_ADJ man_N prepares_TV dinner_N" },
  { label: 1, text: "skillful_ADJ woman_N cooks_TV sauce_N" },
  { label: 0, text: "woman_N runs_TV useful_ADJ program_N" },
  { label: 0, text: "skillful_ADJ person_N runs_TV software_N" },
  { label: 0, text: "skillful_ADJ person_N prepares_TV program_N" },
  { label: 1, text: "man_N prepares_TV sauce_N" },
  { label: 1, text: "person_N cooks_TV tasty_ADJ sauce_N" },
  { label: 1, text: "man_N cooks_TV sauce_N" },
  { label: 0, text: "man_N prepares_TV program_N" },
  { label: 0, text: "skillful_ADJ person_N prepares_TV software_N" },
  { label: 1, text: "woman_N bakes_TV meal_N" },
  { label: 1, text: "skillful_ADJ man_N bakes_TV sauce_N" },
  { label: 0, text: "man_N prepares_TV useful_ADJ software_N" },
  { label: 0, text: "woman_N debugs_TV program_N" },
  { label: 0, text: "skillful_ADJ woman_N runs_TV application_N" },
  { label: 0, text: "man_N debugs_TV software_N" },
  { label: 0, text: "skillful_ADJ woman_N debugs_TV application_N" },
  { label: 0, text: "person_N debugs_TV software_N" },
  { label: 1, text: "person_N bakes_TV meal_N" },
  { label: 1, text: "skillful_ADJ woman_N bakes_TV dinner_N" },
  { label: 1, text: "skillful_ADJ woman_N cooks_TV dinner_N" },
  { label: 0, text: "woman_N runs_TV useful_ADJ software_N" },
  { label: 1, text: "man_N cooks_TV meal_N" },
  { label: 0, text: "person_N debugs_TV program_N" },
  { label: 1, text: "woman_N bakes_TV sauce_N" },
  { label: 0, text: "skillful_ADJ woman_N debugs_TV software_N" },
  { label: 1, text: "woman_N prepares_TV meal_N" },
];
